filesystem:
  allowed_roots:
  - N:\OneDrive - Université Cheikh Anta DIOP de DAKAR\PycharmProjects\aNtaerus\antaerus\docs
  - N:\OneDrive - Université Cheikh Anta DIOP de DAKAR\PycharmProjects\aNtaerus\antaerus\memory_data
  - N:\OneDrive - Université Cheikh Anta DIOP de DAKAR\PycharmProjects\aNtaerus\antaerus\providers\brain_python
  - C:\Users\DELL\Downloads\THIOR\ALPHA BLONDY
  - C:\Users\DELL\Downloads\THIOR
meta:
  generator: antaerus_brain
  id: b3c8a79e-ddb9-4172-95d9-35199b498c7f
  updated_at: '2026-08-27T03:59:22+00:00'
