filesystem:
  allowed_roots:
  - N:\OneDrive - Université Cheikh Anta DIOP de DAKAR\PycharmProjects\aNtaerus\antaerus\docs
  - N:\OneDrive - Université Cheikh Anta DIOP de DAKAR\PycharmProjects\aNtaerus\antaerus\memory_data
  - N:\OneDrive - Université Cheikh Anta DIOP de DAKAR\PycharmProjects\aNtaerus\antaerus\providers\brain_python
  - C:\Users\DELL\Downloads\THIOR\ALPHA BLONDY
  - C:\Users\DELL\Downloads\THIOR
meta:
  generator: antaerus_brain
  id: 1528c130-d34b-4eb4-b6b6-f05281f68ab2
  updated_at: '2026-08-27T03:44:12+00:00'
